" let pathogen handle plugin load
call pathogen#helptags()
call pathogen#runtime_append_all_bundles()

" change the mapleader from \ to ,
let mapleader=","

set hidden
set termencoding=utf-8
set backspace=indent,eol,start
set fileencodings=ucs-bom,utf-8,default,latin1
set guifont=Droid\ Sans\ Mono\ 10
set fileformats=unix,dos
set history=2000
set undolevels=2000
set wildignore=*.swp,*.bak,*.pyc,*.class
set title
set ruler
set number
set mouse=a
set noerrorbells
set visualbell
"set nobackup
"set noswapfile
set showmatch
set laststatus=2
set nowrap
syntax on
filetype plugin indent on
set autoindent
set copyindent
"set smartindent
set expandtab tabstop=4 shiftwidth=4
set shiftround
set smartcase
set ignorecase
set smarttab
set hlsearch
set incsearch
set pastetoggle=<F2>

" Easy window navigation
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
map <C-H> <C-W>h
map <C-L> <C-W>l
map <C-E> <C-W>=
map <C-B> <C-W><bar>

map <C-P> :set paste<Return>
map <C-A> :set nopaste<Return>
set wmw=0
set wmh=0
nnoremap <silent> <F8> :TlistToggle<CR>
nmap <silent> ,/ :nohlsearch<CR>
colors desert

" Remap for Command-t
noremap <leader>o <Esc>:CommandT<CR>
noremap <leader>O <Esc>:CommandTFlush<CR>
noremap <leader>m <Esc>:CommandTBuffer<CR>

" Use CloseTag for certain filetypes
autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim

" Set the php doc block config
" let g:pdv_cfg_Package = 
" Map php doc block
inoremap <C-B> <ESC>:call PhpDocSingle()<CR>i
nnoremap <C-B> :call PhpDocSingle()<CR>
vnoremap <C-B> :call PhpDocRange()<CR> 

" Show evil tabs
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.
autocmd filetype html,xml set listchars-=tab:>.

nnoremap ; :

nmap <F8> :TagbarToggle<CR>

:autocmd FileType php noremap <C-Y> :w!<CR>:!php %<CR>
:autocmd FileType php noremap <C-N> :!php -l %<CR>

" Make editing sudo required files easier
cmap w!! w !sudo tee % >/dev/null

" Set status line to include git branch
set statusline=%f\ %{fugitive#statusline()}%r%m%=%c,%l/%L\ %P

" Swap and backup locations
set backupdir=~/.backup/vim/,./.backup/vim,.,/tmp
set directory=~/.backup/swap/,.,./.backup/swap,/tmp
set autoread

" GUI settings
if has('gui_running')
    colorscheme mustang
    nmap <C-V> "+gP
    imap <C-V> <ESC><C-V>i
    vmap <C-C> "+y
endif
