set nocompatible              " be iMproved, required
filetype off                  " required

" enable matchit plugin which ships with vim and greatly enhances '%'
runtime macros/matchit.vim

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundles/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'wincent/command-t'
Plugin 'vim-scripts/php.vim--Garvin'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'groenewege/vim-less'
Plugin 'phpvim/phpcd.vim', { 'for': 'php' , 'do': 'composer update' }
Plugin 'dracula/vim', { 'name': 'dracula' }

" All of your Plugins must be added before the following line
call vundle#end()            " required
colorscheme dracula
filetype plugin indent on    " required

" change the mapleader from \ to ,
let mapleader=","

" set some defaults
set hidden
set termencoding=utf-8
set backspace=indent,eol,start
set fileencodings=ucs-bom,utf-8,default,latin1
set guifont=Droid\ Sans\ Mono\ 10
set fileformats=unix,dos
set history=2000
set undolevels=2000
set wildignore=*.swp,*.bak,*.pyc,*.class
set title
set ruler
set number
set mouse=a
set noerrorbells
set visualbell
"set nobackup
"set noswapfile
set showmatch
set laststatus=2
set nowrap
syntax on
set autoindent
set copyindent
"set smartindent
set expandtab tabstop=4 shiftwidth=4
set shiftround
set smartcase
set ignorecase
set smarttab
set hlsearch
set incsearch
set wmw=0
set wmh=0
set pastetoggle=<F2>
"colors desert
nnoremap ; :

" Easy window navigation
map <C-J> <C-W>j<C-W>_
map <C-K> <C-W>k<C-W>_
map <C-H> <C-W>h
map <C-L> <C-W>l
map <C-E> <C-W>=
map <C-B> <C-W><bar>

" easy pasting
map <C-P> :set paste<Return>
map <C-A> :set nopaste<Return>

" Show evil tabs
set list
set listchars=tab:>.,trail:.,extends:#,nbsp:.
autocmd filetype html,xml set listchars-=tab:>.

" Make editing sudo required files easier
cmap w!! w !sudo tee % >/dev/null

" Set status line to include git branch
set statusline=%f\ %{fugitive#statusline()}%r%m%=%c,%l/%L\ %P

" Swap and backup locations
set backupdir=~/.backup/vim/,./.backup/vim,.,/tmp
set directory=~/.backup/swap/,.,./.backup/swap,/tmp
set autoread
