# add paths to home folder
PATH=$PATH:~/bin:/opt/vagrant/bin

SITE_ENV=development
KOHANA_ENV=$SITE_ENV

#alias composer='php ~/bin/composer.phar'
if [ -f ~/dotfiles/git/git-autocomplete.sh ]; then
    . ~/dotfiles/git/git-autocomplete.sh
fi

alias android-connect="mtpfs -o allow_other /media/GalaxyNexus"
alias android-disconnect="fusermount -u /media/GalaxyNexus"

#export VAGRANT_HOME="/media/disc/vagrant.d"
